apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: flask-app
  annotations:
    # Tell AWS to create an internet-facing load balancer
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  type: LoadBalancer
  selector:
    app: flask-webapp
  ports:
    - protocol: TCP
      port: 80          # External port — users hit port 80
      targetPort: 5000  # Internal port — Flask listens on 5000