apiVersion: v1
kind: Pod
metadata:
  name: configmap-test
  namespace: devops-learning
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: APP_PORT
      valueFrom:
        configMapKeyRef:
          name: my-config
          key: APP_PORT
    - name: LOG_LEVEL
      valueFrom:
        configMapKeyRef:
          name: my-config
          key: LOG_LEVEL
    - name: ENVIRONMENT
      valueFrom:
        configMapKeyRef:
          name: my-config
          key: ENVIRONMENT
