apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-config
  namespace: flask-app
  labels:
    project: flask-webapp
data:
  APP_MESSAGE: "Hello from Kubernetes!"
  ENVIRONMENT: "development"
  APP_VERSION: "1.0.0"
